### ISSUE TITLE
File Dialogs don't show up for Linux

### ISSUE THREAD

**Issue by LeNitrous** [LeNitrous/sbtw#2]
This is due to the library `tinyfiledialogs64` not being found.

**Comment by sr229** [comment]
You'll want to create a out-of-tree CMake build script like so and do it yourself (or have it in-tree and PR it to tinyfiledialogs)

**Comment by LeNitrous** [comment]
This should be resolved when `nativefiledialogs-extended` replaces `tinyfiledialogs`
